### ISSUE TITLE
Unavailable classes

### ISSUE THREAD

**Issue by david-shortman** [MountainSOLSchool/platform#33]
**Given**
I am a parent/student
AND
I am using the app during Summer 2023
**When**
I am on the enrollment class list page
AND
A class is marked as unavailable by a developer
**Then**
The class card is disabled and there is a label that says "Unavailable"

Tech notes:
- just a db flag + conditional frontend style behavior

**Comment by katiez07** [comment]
I checked in with Jen and she said we can just bring in extra teachers to cover the case where there are too many kids enrolled! So this can probably be backlogged

**Comment by katiez07** [comment]
Might be nice to have the capability but not a priority

**Comment by katiez07** [comment]
Want this to be a button on admin portal to disable class

**Comment by katiez07** [comment]
New thought: maybe actually we should work this one soonish, because there are already 12 students in forts! Jen might not realize how many there are lol
